name: Deploy to Render
on:
  push:
    branches: [ "main" ]  # Triggers on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        uses: render-actions/deploy@v1
        with:
          cloud: render
          service-id: "your-render-service-id"  # Replace with your Render service ID
          api-key: ${{ secrets.RENDER_API_KEY }}
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  # Passes secret to Render
